yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AuthorView.as_view(), name='author'),
    path('tech/', views.TechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'password_reset/done/',
        views.password_reset_done,
        name='password_reset_done'
    ),
    path(
        'password_reset/<uidb64>/<token>/',
        views.password_reset_confirm,
        name='password_reset_confirm'
    ),
    path(
        'password_reset/complete/',
        views.password_reset_complete,
        name='password_reset_complete'
    ),
    path(
        'password_change/',
        views.password_change,
        name='password_change'
    ),
    path(
        'password_change/done/',
        views.password_change_done,
        name='password_change_done'
    ),
    path(
        'password_reset/',
        views.password_reset,
        name='password_reset'
    ),
    path('contact/', views.ContactView.as_view(), name='contact')
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.page_forbidden'
handler500 = 'core.views.page_server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/article.html
{% load thumbnail %}
<article>
  <ul>
    <li>
      Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a> 
  {% if post.group %}   
    | <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if post.author.username == user.username%}
     | <a href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>
  {% endif %}
</article>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <ul class="nav justify-content-center" style="color:red">

    <li class ="nav-item">  
      <a class="nav-link" href="{% url 'users:contact'%}">Письмо администраторам</a>
    </li> 
    <li class ="nav-item">  
      <a class="nav-link" href="{% url 'about:author'%}">Об авторе</a>
    </li> 
    <li class ="nav-item">  
      <a class="nav-link" href="{% url 'about:tech'%}">О технологиях проекта</a>
    </li> 
  </ul>
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
    <p>© 2022 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static%}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {# Добавлено в спринте #}

      {% comment %}
      Я считаю, что ссылки на страницы about/ лучше поставить в footer, а не в header. Мне так визуально больше нравится.
      {% endcomment %}

      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        {% if user.is_authenticated %}
        
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}" href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:password_reset' %}active{% endif %}" href="{% url 'users:password_reset' %}">Сбросить пароль</a>
        </li>        
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'posts:profile' %}active{% endif %}" href="{% url 'posts:profile' user.username %}">Пользователь: {{ user.username }}</a>
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}
      {# Конец добавленого в спринте #}
    </div>
  </nav>      
</header> 

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<div class="position-relative">
    <nav aria-label="Page navigation" class="my-5 position-absolute top-50 start-50 translate-middle">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1"><<<</a></li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <
            </a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active">
                <span class="page-link">{{ i }}</span>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            >>>
            </a>
        </li>
            {% endif %}    
    </ul>
    </nav>
</div>
{% endif %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}
 