yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AuthorView.as_view(), name='author'),
    path('tech/', views.TechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'password_reset/done/',
        views.password_reset_done,
        name='password_reset_done'
    ),
    path(
        'password_reset/<uidb64>/<token>/',
        views.password_reset_confirm,
        name='password_reset_confirm'
    ),
    path(
        'password_reset/complete/',
        views.password_reset_complete,
        name='password_reset_complete'
    ),
    path(
        'password_change/',
        views.password_change,
        name='password_change'
    ),
    path(
        'password_change/done/',
        views.password_change_done,
        name='password_change_done'
    ),
    path(
        'password_reset/',
        views.password_reset,
        name='password_reset'
    ),
    path('contact/', views.ContactView.as_view(), name='contact')
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.page_forbidden'
handler500 = 'core.views.page_server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/models.py
from django.db import models


class SignUp(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    email = models.CharField(max_length=200)


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    body = models.TextField()
    is_answered = models.BooleanField(default=False)

yatube/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Contact

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'body')

yatube/users/views.py
from django.core.mail import send_mail
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic.edit import CreateView

from .forms import ContactForm, CreationForm
from .models import Contact


class SignUpView(CreateView):
    form_class = CreationForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('posts:index')


class ContactView(CreateView):
    form_class = ContactForm
    template_name = 'users/contact.html'
    contact = Contact()
    form = ContactForm(instance=contact)
    context = {'form': form}
    success_url = reverse_lazy('posts:index')


class LoginView(CreateView):
    template_name = 'users/login.html'
    success_url = reverse_lazy('posts:index')


class LogoutView(CreateView):
    template_name = 'users/logout.html'


def password_change(request):
    template = 'users/password_change_form.html'
    return render(request, template)


def password_change_done(request):
    template = 'users/password_change_done.html'
    return render(request, template)


def password_reset(request):
    template = 'users/password_reset_form.html'
    return render(request, template)


def password_reset_done(request):
    template = 'users/password_reset_done.html'
    send_mail('Сброс пароля',
              'Чтобы сбросить пароль, перейдите по ссылке: ',
              'from@example.com',
              ['to@example.com'],
              fail_silently=False,)
    return render(request, template)


def password_reset_confirm(request):
    template = 'users/password_reset_confirm.html'
    return render(request, template)


def password_reset_complete(request):
    template = 'users/password_reset_complete.html'
    return render(request, template)

yatube/templates/users/contact.html
<!DOCTYPE html> 
{% extends 'base.html'%}
    {% block title %}<title>Письмо администратору</title>{% endblock %}
    {% block content %}  
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Отправить сообщение администраторам
            </div>
            <div class="card-body">    
                <form method="post" action="{% url 'users:contact' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Отправить">
                </form> 
            </div>
          </div>
      </div>
    </div>
    {% endblock %}

yatube/templates/users/logged_out.html
<!DOCTYPE html> 
{% extends 'base.html'%}
    {% block title %}<title>Зарегистрироваться</title>{% endblock %}
    {% block content %}  
  <body>	   
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">Выход</div>
              <div class="card-body"> <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row --> 
      </div>
    </main>
  </body>
  {% endblock %}
</html>

yatube/templates/users/login.html
<!DOCTYPE html> 
{% extends 'base.html'%}
    {% block title %}<title>Войти в профиль</title>{% endblock %}
    {% block content %}  
    {% load user_filters %}
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Войти на сайт
            </div>
            <div class="card-body">
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
    
              <form method="post"
                {% if action_url %}
                  action="{% url action_url %}"
                {% endif %}
              >
              {% csrf_token %}
    
              {% for field in form %}
                <div class="form-group row my-3"
                  {% if field.field.required %} 
                    aria-required="true"
                  {% else %}
                    aria-required="false"
                  {% endif %}
                >
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  <div>
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Войти
                </button>
                <!-- Тест на внимательность. Без переопределения шаблона этого адреса
                не существует. Нужно что-то делать, иначе все упадет -->
                <a href="{% url 'users:password_reset' %}" class="btn btn-link">
                  Забыли пароль?
                </a>
              </div>
              </form>
            </div> <!-- card body -->
          </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->
    {% endblock %} 

yatube/templates/users/password_change_done.html
<!DOCTYPE html> 
{% extends 'base.html'%}
    {% block title %}<title>Сменить пароль</title>{% endblock %}
    {% block content %}  
  </head>
  <body>	   
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
  </body>
  {% endblock %}
</html>

yatube/templates/users/password_change_form.html
<!DOCTYPE html> 
{% extends 'base.html'%}
    {% block title %}<title>Сменить пароль</title>{% endblock %}
    {% block content %}  
  <body>	   
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="done/">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
  </body>
  {% endblock %}
</html>

yatube/templates/users/password_reset_complete.html
<!DOCTYPE html> 
{% extends 'base.html'%}
    {% block title %}<title>Пароль сменён успешно!</title>{% endblock %}
    {% block content %}  
  <body>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="../users/login.html">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
  </body>
  {% endblock %}
</html>

yatube/templates/users/password_reset_confirm.html
<!DOCTYPE html> 
<!DOCTYPE html> 
{% extends 'base.html'%}
    {% block title %}<title>Новый пароль</title>{% endblock %}
    {% block content %}  
  <body>	   
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/lpassword_reset_confirm.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                    </small>      
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- если использована неправильная ссылка -->
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Ошибка
              </div>
              <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- конец если использована неправильная ссылка -->
      </div>
    </main>
  </body>
  {% endblock %}
</html>

yatube/templates/users/password_reset_done.html
<!DOCTYPE html> 
<!DOCTYPE html> 
{% extends 'base.html'%}
    {% block title %}<title>Пароль сменён успешно!</title>{% endblock %}
    {% block content %}  
  <body>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
  </body>
  {% endblock %}
</html>

yatube/templates/users/password_reset_form.html
<!DOCTYPE html> 
{% extends 'base.html'%}
    {% block title %}<title>Смена пароля</title>{% endblock %}
    {% block content %}  
  <body>	   
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="post" action="done/">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
    </main>
  </body>
  {% endblock %}
</html>

yatube/templates/users/signup.html
{% extends 'base.html'%}
{% block title %}<title>Зарегистрироваться</title>{% endblock %}
{% block content %}  
  <body>	   
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
              <div class="card">
                <div class="card-header">
                  Зарегистрироваться
                </div>
                <div class="card-body">
                  <form method="post" action="{% url 'users:signup' %}">
                    {% csrf_token %}
                    <div class="form-group row my-3 p-3">
                      <label for="id_first_name">Имя</label>    
                      <input type="text" name="first_name" maxlength="30" class="form-control" id="id_first_name">     
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_last_name">Фамилия</label>    
                      <input type="text" name="last_name" maxlength="150" class="form-control" id="id_last_name">
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_username">
                        Имя пользователя
                        <span class="required text-danger">*</span>
                      </label>    
                      <input type="text" name="username" maxlength="150" autofocus class="form-control" required id="id_username">
                        <small id="id_username-help" class="form-text text-muted">
                          Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
                        </small>
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_email">Адрес электронной почты</label>    
                      <input type="email" name="email" maxlength="254" class="form-control" id="id_email">      
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_password1">
                        Пароль        
                        <span class="required text-danger">*</span>
                      </label>    
                      <input type="password" name="password1" class="form-control" required id="id_password1">
                      <small id="id_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                    </div>
                    <div class="form-group row my-3 p-3">
                      <label for="id_password2">
                        Подтверждение пароля
                        <span class="required text-danger">*</span>
                      </label>    
                      <input type="password" name="password2" class="form-control" required id="id_password2">
                      <small id="id_password2-help" class="form-text text-muted">
                        Для подтверждения введите, пожалуйста, пароль ещё раз.
                      </small>
                    </div>
                    <div class="col-md-6 offset-md-4">
                      <button type="submit" class="btn btn-primary">
                        Зарегистрироваться
                      </button>
                    </div>
                  </form>
                </div> <!-- card body -->
              </div> <!-- card -->
            </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
  </body>
{% endblock %}